### ISSUE TITLE
Support for custom time formats?

### ISSUE THREAD

**Issue by GuyPaddock** [hsiafan/gson-java8-datatype#2]
It would be great if there was a way to provide the String pattern describing the date format that's being parsed or exported.

**Comment by clearthesky** [comment]
Java8 DateTime has multi different types, hard to use the same format string.
Maybe could set custom DateTimeFormatter instance for each separated Java8 DateTime types( Instant, LocalDateTime, ZonedDateTime, etc)

**Comment by GuyPaddock** [comment]
Right now, what I've done in my project is defined a public subclass of `Java8TimeAdapter` in the `net.dongliu.gson` package (since that class is currently only package-visible). The existing constructor for `Java8TimeAdapter` seems to be sufficient for our needs as long as we manually register the type adapters instead of using `GsonJava8TypeAdapterFactory`.

It would be ideal if there was a way to register a list of acceptable time formats with a given time adapter instance, and then have it try parsing them until it finds a match.

**Comment by hsiafan** [comment]
Now can set custom DateTimeFormatter for each DateTime type: https://github.com/hsiafan/gson-java8-datatype#custom-datetimeformatter

**Comment by GuyPaddock** [comment]
Awesome! Thank you :)
